import type { Metadata } from "next";
import { Inter, Trispace } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const trispace = Trispace({
  variable: "--font-trispace",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Fellipe Mayan - Designer de Produto + Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`
          ${inter.variable} 
          ${trispace.variable}
        `}
      >
        {children}
      </body>
    </html>
  );
}
