import type { Metadata } from 'next'
import { Inter, Trispace } from 'next/font/google'
import { Header } from './components/header/Header'
import './globals.css'
import { Footer } from './components/footer/Footer'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

const trispace = Trispace({
  variable: '--font-trispace',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Fellipe Mayan - Designer de Produto + Dev',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
            (function() {
              try {
                var theme = localStorage.getItem('portfolio-theme');
                var scheme = theme === 'system'
                  ? (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light')
                  : theme;
                document.documentElement.setAttribute('data-theme', scheme || 'light');
              } catch(e) {}
            })();
          `,
          }}
        />
      </head>
      <body
        className={`
          ${inter.variable} 
          ${trispace.variable}
          content-grid
        `}
      >
        <Header />
        <main className="full-width">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
